type DiffDirection = 'higher' | 'lower' | 'equal'

interface TipEntry {
  higher: string
  lower: string
}

// Returns a behavioral description based on what changed and in which direction.
// "higher" means the Compare setup has a higher value than Baseline.
// "lower" means the Compare setup has a lower value than Baseline.
const tips: Record<string, Record<string, TipEntry>> = {
  'Tyres & Alignment': {
    'Tyre Pressure': {
      higher: 'Higher pressures sharpen initial turn-in and reduce rolling resistance, but the smaller contact patch lowers overall grip — especially as tyres overheat in longer stints. ACC\'s optimal window is around 27.5 PSI (hot) for dry conditions.',
      lower: 'Lower pressures widen the contact patch, increasing mechanical grip. The trade-off is sluggish initial turn-in and extra heat generated by sidewall flex. If pressures drop too far below the optimal window, grip falls off again as the tyre deforms excessively.',
    },
    'Toe Front': {
      higher: '', // handled by special toe logic
      lower: '',
    },
    'Toe Rear': {
      higher: '',
      lower: '',
    },
    'Camber Front': {
      higher: 'Less negative front camber. The tyre sits flatter on the road, which improves braking grip in a straight line but reduces the contact patch available during cornering. Check your front tyre temps — if the outside edge is hotter than the inside, you may need more negative camber.',
      lower: 'More negative front camber. The tyre leans into the turn, putting more rubber on the road through corners and improving front grip. Straight-line braking may suffer slightly. Watch for the inside edge running too hot — that means you\'ve gone too far.',
    },
    'Camber Rear': {
      higher: 'Less negative rear camber. The rear tyres sit flatter, improving traction under straight-line acceleration. However, the rear loses cornering grip, which can increase oversteer through sustained turns.',
      lower: 'More negative rear camber. The rear gains cornering grip, making the car more stable and planted through turns. Traction under hard acceleration may be slightly reduced. The rear is more sensitive to camber changes than the front — small adjustments have a noticeable effect.',
    },
    'Caster': {
      higher: 'Higher caster increases straight-line stability and generates more dynamic camber gain as you turn the wheel, giving the front tyres better grip on corner entry. However, too much caster creates mid-corner understeer as the excessive camber gain loads the outside tyre unevenly. Steering effort also increases.',
      lower: 'Lower caster reduces straight-line stability and limits the dynamic camber gain during cornering, meaning less front grip on turn-in. Steering feels lighter and the car may wander slightly on straights.',
    },
  },

  'Electronics': {
    'TC1': {
      higher: 'Higher TC1 increases the traction control threshold, intervening earlier via spark cut — a sharp, binary method that momentarily kills ignition to limit wheelspin. The car is much easier to manage on corner exit but acceleration suffers from the aggressive power interruptions.',
      lower: 'Lower TC1 allows more wheelspin before traction control activates. Faster on exit if you can manage the throttle precisely, but the rear can snap loose. TC1 and TC2 work best when kept within one or two steps of each other.',
    },
    'TC2': {
      higher: 'Higher TC2 increases traction control sensitivity via spark retard — a smoother, more progressive method that reduces ignition timing to limit power. This makes exits very safe and predictable, but noticeably slower. Not all cars expose TC2.',
      lower: 'Lower TC2 reduces the progressive power reduction during traction events. The car delivers more power on exit but requires cleaner throttle inputs. Keep TC2 within one or two steps of TC1 for best results.',
    },
    'ABS': {
      higher: 'Higher ABS allows more electronic intervention to prevent lock-ups. Braking zones are more forgiving — useful on unfamiliar tracks or in changing conditions — but stopping distances increase because the system limits peak braking force.',
      lower: 'Lower ABS reduces electronic intervention, allowing you to threshold-brake closer to the tyre\'s actual grip limit. Shorter stopping distances are possible, but you are far more likely to lock a wheel under heavy braking or trail-braking.',
    },
    'ECU Map': {
      higher: 'Higher ECU map numbers typically reduce power output to save fuel and manage engine heat — useful for long stints, wet conditions, or safety car periods. Note: ECU maps are car-specific. Some cars (notably the Porsche 991 GT3-R) use higher map numbers for qualifying power, which inverts this general rule. Always check your car\'s specific map table.',
      lower: 'Lower ECU map numbers generally provide maximum power — best for qualifying and sprint races. Fuel consumption increases. Again, this varies by car: some models (like the Honda NSX) have multiple full-power maps that only differ in throttle response curve.',
    },
  },

  'Mechanical Grip': {
    'Anti-Roll Bar Front': {
      higher: 'Stiffer front anti-roll bar reduces body roll and sharpens the car\'s initial response to steering input — the car rotates faster into the turn. However, the stiffer bar transfers load to the outside front tyre more aggressively, which can overwhelm its grip and cause understeer, especially in slower corners and on bumpy surfaces.',
      lower: 'Softer front anti-roll bar allows more body roll, which keeps both front tyres loaded more evenly and increases total front mechanical grip. This reduces understeer on corner entry, but the car\'s initial response to steering input will feel lazier and less direct. Better for tracks with lower-speed corners or rough surfaces.',
    },
    'Anti-Roll Bar Rear': {
      higher: 'Stiffer rear anti-roll bar reduces body roll at the rear, transferring load to the outside rear tyre more aggressively. This reduces rear mechanical grip in corners, promoting oversteer — particularly on exit as the inside rear unloads. A stiffer rear ARB also helps keep the rear ride height stable, which can improve diffuser efficiency at speed.',
      lower: 'Softer rear anti-roll bar allows more body roll at the rear, keeping both rear tyres better loaded and improving traction. This reduces oversteer on corner exit and makes the car more forgiving, but the rear may feel less precise during quick transitions.',
    },
    'Diff Preload': {
      higher: 'Higher diff preload locks the rear wheels together more firmly. In low-gear corners, this stabilizes the car on entry and under braking but can cause oversteer on acceleration as the locked inside wheel pushes. In high-gear corners, the effect reverses — higher preload creates understeer on both entry and exit because engine torque isn\'t high enough relative to the preload to generate a meaningful speed difference between the wheels.',
      lower: 'Lower diff preload lets the rear wheels differentiate speed more freely. The car rotates more easily on corner entry and can put power down more cleanly in low-gear exits. Under braking, the rear may feel less stable as the unlocked diff allows small speed differences to develop between the rear tyres.',
    },
    'Brake Power': {
      higher: 'Higher brake power increases the maximum braking force available at full pedal input. Stopping distances shorten, but lock-ups become more likely — especially if your ABS is set low. Requires precise pedal modulation.',
      lower: 'Lower brake power reduces the maximum force at full pedal input. Braking is more progressive and easier to modulate, which can help consistency, but stopping distances increase.',
    },
    'Brake Bias': {
      higher: 'More forward brake bias puts more braking force on the front axle. This improves stability and predictability under heavy braking, but the fronts can lock first and the car may understeer on corner entry during trail-braking.',
      lower: 'More rearward brake bias shifts braking force to the rear axle. This helps rotate the car into corners during trail-braking, but increases the risk of rear lock-ups and snap oversteer. Most GT3 cars run between 56–60% front.',
    },
    'Steering Ratio': {
      higher: 'Higher steering ratio means more steering wheel rotation is needed for the same front wheel angle. The car feels calmer and more predictable, which suits fast circuits with long sweeping turns. Quick corrections require more hand movement.',
      lower: 'Lower steering ratio means less steering wheel rotation is needed. The car responds faster to inputs, which suits tight and technical circuits. On fast tracks, the extra sensitivity can feel twitchy and make smooth inputs harder.',
    },
    'Wheel Rate Front': {
      higher: 'Stiffer front springs reduce body pitch under braking and improve high-speed responsiveness by keeping the front ride height more consistent — which matters for aero. The front may lose grip on bumpy or uneven surfaces as the tyres can\'t follow the road as well.',
      lower: 'Softer front springs allow the tyres to follow the road surface better, improving front mechanical grip on bumps. However, the front end dives more under braking and the ride height changes more, which can destabilize the aero platform. If springs are too soft, the car rides on its bumpstops constantly, which hurts grip.',
    },
    'Wheel Rate Rear': {
      higher: 'Stiffer rear springs reduce squat under acceleration and keep the rear ride height more stable, helping diffuser performance. Rear traction may suffer on bumpy surfaces as the tyres skip over irregularities.',
      lower: 'Softer rear springs improve rear traction over bumps and uneven surfaces by allowing the tyres to maintain contact better. The rear will squat more under acceleration and the ride height variation can reduce diffuser efficiency.',
    },
    'Bumpstop Rate Front': {
      higher: 'Stiffer front bumpstops resist compression more firmly once the suspension bottoms out. This creates a harder floor for the aero platform, improving stability and responsiveness under hard braking. On rough surfaces, the stiff bumpstop transmits more force into the chassis, which can cause understeer.',
      lower: 'Softer front bumpstops absorb impacts more gradually when the suspension reaches full travel, improving front grip over bumps and aggressive kerbs. The front ride height becomes less consistent, which can affect aero balance.',
    },
    'Bumpstop Rate Rear': {
      higher: 'Stiffer rear bumpstops improve rear stability during hard acceleration and corner exit by creating a firm limit to rear compression. Traction may suffer on bumpy tracks as sharp forces transfer through to the chassis.',
      lower: 'Softer rear bumpstops improve rear traction over bumps and kerbs by absorbing energy more progressively. If too soft, the rear can compress too far under load, causing unpredictable ride height changes and oversteer.',
    },
    'Bumpstop Range Front': {
      higher: 'More free suspension travel before the bumpstop engages. The front end absorbs road irregularities better, relying on the springs and dampers rather than the bumpstop rubber. Turn-in may feel slightly less direct as the suspension has more freedom to move. GT3 cars in ACC often run on their front bumpstops almost continuously — increasing the range moves away from that behavior.',
      lower: 'Less free travel before the bumpstop engages — the suspension hits the rubber earlier in its stroke. This effectively stiffens the front end and creates a more rigid aero platform with sharper turn-in response. Grip may suffer on rough surfaces as the bumpstop takes over earlier.',
    },
    'Bumpstop Range Rear': {
      higher: 'More rear suspension travel before the bumpstop engages. This improves traction and stability over bumps and through fast corners by letting the springs and dampers do most of the work. The rear may feel softer and less responsive on exit.',
      lower: 'Less rear suspension travel before the bumpstop engages. The rear becomes stiffer and more responsive sooner in its stroke, but traction over rough surfaces is reduced as the bumpstop takes load earlier.',
    },
  },

  'Dampers': {
    'Bump Front': {
      higher: 'Higher front bump (compression) damping slows how quickly the front suspension compresses. The front resists dive under braking, keeping the car more level and the aero platform stable. Too high and the front tyres can\'t follow the road over bumps, losing grip.',
      lower: 'Lower front bump damping lets the suspension compress more freely. Weight transfers to the front faster under braking, which can improve front grip on uneven surfaces. The car dives more into braking zones.',
    },
    'Bump Rear': {
      higher: 'Higher rear bump damping resists rear compression, improving stability during braking and corner entry by slowing how quickly weight leaves the rear. Too much can reduce rear traction over bumps as the tyres skip instead of following the surface.',
      lower: 'Lower rear bump damping allows the rear to compress more easily. Improves traction on rough surfaces but the rear may squat more under acceleration and feel less controlled during weight transfer.',
    },
    'Fast Bump Front': {
      higher: 'Higher front fast bump damping controls how the suspension reacts to sudden sharp impacts — kerbs, sharp bumps, and surface transitions. Higher values prevent bottoming out but transmit more force to the chassis, which can unsettle the car over aggressive kerbing.',
      lower: 'Lower front fast bump damping lets the suspension absorb sharp impacts more freely. Better compliance over kerbs and rumble strips, but the suspension may bottom out more easily on heavy compressions.',
    },
    'Fast Bump Rear': {
      higher: 'Higher rear fast bump damping limits how quickly the rear compresses over sharp bumps and kerbs. Improves control when riding kerbs aggressively but can reduce grip on very rough surfaces as the rear skips.',
      lower: 'Lower rear fast bump damping lets the rear absorb sharp impacts more freely. Better for tracks with aggressive kerbs or rough surfaces, but the rear may bottom out and become unstable if the impacts exceed the available travel.',
    },
    'Rebound Front': {
      higher: 'Higher front rebound damping slows how quickly the front suspension extends back after being compressed. The front settles more gradually after bumps and braking, improving stability during weight transfer. Too much rebound can cause "jacking" — the suspension doesn\'t extend fully before the next compression, progressively lowering the ride height.',
      lower: 'Lower front rebound damping lets the front extend back to full travel faster. The car responds more quickly to weight shifting off the front, which can improve turn-in. The front may feel less stable during rapid transitions as it rebounds too aggressively.',
    },
    'Rebound Rear': {
      higher: 'Higher rear rebound damping slows the rear extension after compression. This improves rear stability during transitions and prevents the rear from unloading too quickly on corner exit. Too much can reduce traction if the rear can\'t follow the road surface on successive bumps.',
      lower: 'Lower rear rebound damping lets the rear return to full travel faster. Improves rear traction during quick transitions and over sequences of bumps, but the rear may feel less planted and more unsettled during sustained cornering.',
    },
    'Fast Rebound Front': {
      higher: 'Higher front fast rebound damping controls how quickly the suspension extends after sharp compressions like kerb strikes. Higher values keep the car more settled after hitting kerbs, preventing the suspension from rebounding violently.',
      lower: 'Lower front fast rebound damping allows faster extension after sharp impacts. The suspension recovers to full travel quicker, maintaining ground contact — but may overshoot and feel unsettled over repeated sharp bumps.',
    },
    'Fast Rebound Rear': {
      higher: 'Higher rear fast rebound damping slows the rear extension after sharp impacts. Helps keep the rear stable over sequences of kerbs or bumps by preventing violent rebound oscillation.',
      lower: 'Lower rear fast rebound damping allows faster rear extension after impacts. Better for maintaining traction over rough sections, but the rear can feel unsettled if the extension speed overshoots the natural ride height.',
    },
  },

  'Aero & Ride Height': {
    'Ride Height Front': {
      higher: 'Higher front ride height reduces the Venturi effect under the car, decreasing front downforce. The car has less front grip in corners but is less likely to bottom out or stall the splitter on bumps. In ACC, even 1mm of front ride height change can shift aero balance by 0.5–2%.',
      lower: 'Lower front ride height accelerates airflow under the car, increasing front downforce through ground effect. More front grip in corners, but the car becomes more sensitive to bumps and the splitter can stall if it gets too close to the track surface — causing a sudden loss of front downforce.',
    },
    'Ride Height Rear': {
      higher: 'Higher rear ride height reduces rear downforce by weakening the diffuser\'s efficiency. Less rear grip in corners, potentially increasing oversteer, but the car is more tolerant of bumps and elevation changes without bottoming out.',
      lower: 'Lower rear ride height improves diffuser performance, increasing rear downforce and stability. The car may bottom out over bumps or under heavy acceleration, and going too low can stall the diffuser — causing a sudden loss of rear grip.',
    },
    'Rake': {
      higher: 'More rake (front lower relative to rear) shifts the aerodynamic center of pressure forward, increasing front grip and promoting corner rotation. This comes at the cost of increased drag from the higher frontal area exposure. Note: excessive rake reduces diffuser efficiency as the exit rises too far off the ground.',
      lower: 'Less rake brings front and rear ride heights closer together. This reduces drag, improving straight-line speed, and can improve diffuser efficiency. The car will have less front-biased aero, reducing rotation tendency in corners.',
    },
    'Brake Ducts Front': {
      higher: 'Larger front brake ducts cool the front brakes more effectively, preventing fade during long stints or in hot conditions. The primary penalty is increased aerodynamic drag, which reduces top speed and straight-line acceleration. There is a minor reduction in front downforce as well.',
      lower: 'Smaller front brake ducts reduce drag, preserving top speed. Front brake temperatures will run higher, risking fade during extended heavy braking — particularly on tracks like Bathurst, Spa, or Monza.',
    },
    'Brake Ducts Rear': {
      higher: 'Larger rear brake ducts improve rear brake cooling. The main trade-off is increased drag, not a significant downforce loss. This matters more in endurance events where consistent braking over long stints is critical.',
      lower: 'Smaller rear brake ducts reduce drag but may cause rear brake overheating in demanding conditions. The rear brakes do less work than the fronts, so they generally need less cooling.',
    },
    'Splitter': {
      higher: 'Higher splitter value increases the angle of attack, generating more front downforce. This adds front grip in corners and shifts the aero balance forward — which can increase oversteer as the front gains grip relative to the rear.',
      lower: 'Lower splitter value reduces the angle of attack and front downforce. The front end has less grip, shifting the aero balance rearward and potentially causing understeer in medium and high-speed corners.',
    },
    'Rear Wing': {
      higher: 'More rear wing generates more rear downforce, increasing rear grip and reducing oversteer in medium and high-speed corners. The cost is increased drag — lower top speed and slower acceleration on straights.',
      lower: 'Less rear wing reduces drag, increasing top speed and straight-line performance. Rear grip in corners decreases, making the car more prone to oversteer — especially at higher speeds where aero grip dominates mechanical grip.',
    },
  },
}

// Maps the flat parameter labels to the tip keys.
// The parser outputs labels like "  Front" under a parent header "Anti-Roll Bar".
// We need to map those to the tip keys above.
interface TipMapping {
  category: string
  tipKey: string
}

const parameterTipMap: Record<string, TipMapping> = {
  // Tyres & Alignment — pressures share one tip
  'Tyres & Alignment:Tyre Pressure:  FL': { category: 'Tyres & Alignment', tipKey: 'Tyre Pressure' },
  'Tyres & Alignment:Tyre Pressure:  FR': { category: 'Tyres & Alignment', tipKey: 'Tyre Pressure' },
  'Tyres & Alignment:Tyre Pressure:  RL': { category: 'Tyres & Alignment', tipKey: 'Tyre Pressure' },
  'Tyres & Alignment:Tyre Pressure:  RR': { category: 'Tyres & Alignment', tipKey: 'Tyre Pressure' },
  'Tyres & Alignment:Toe:  Front': { category: 'Tyres & Alignment', tipKey: 'Toe Front' },
  'Tyres & Alignment:Toe:  Rear': { category: 'Tyres & Alignment', tipKey: 'Toe Rear' },
  'Tyres & Alignment:Camber:  Front': { category: 'Tyres & Alignment', tipKey: 'Camber Front' },
  'Tyres & Alignment:Camber:  Rear': { category: 'Tyres & Alignment', tipKey: 'Camber Rear' },
  'Tyres & Alignment:Caster:  Left': { category: 'Tyres & Alignment', tipKey: 'Caster' },
  'Tyres & Alignment:Caster:  Right': { category: 'Tyres & Alignment', tipKey: 'Caster' },

  // Electronics
  'Electronics:TC1': { category: 'Electronics', tipKey: 'TC1' },
  'Electronics:TC2': { category: 'Electronics', tipKey: 'TC2' },
  'Electronics:ABS': { category: 'Electronics', tipKey: 'ABS' },
  'Electronics:ECU Map': { category: 'Electronics', tipKey: 'ECU Map' },

  // Mechanical Grip
  'Mechanical Grip:Anti-Roll Bar:  Front': { category: 'Mechanical Grip', tipKey: 'Anti-Roll Bar Front' },
  'Mechanical Grip:Anti-Roll Bar:  Rear': { category: 'Mechanical Grip', tipKey: 'Anti-Roll Bar Rear' },
  'Mechanical Grip:Diff Preload': { category: 'Mechanical Grip', tipKey: 'Diff Preload' },
  'Mechanical Grip:Brake Power': { category: 'Mechanical Grip', tipKey: 'Brake Power' },
  'Mechanical Grip:Brake Bias': { category: 'Mechanical Grip', tipKey: 'Brake Bias' },
  'Mechanical Grip:Steering Ratio': { category: 'Mechanical Grip', tipKey: 'Steering Ratio' },
  'Mechanical Grip:Wheel Rate:  Front': { category: 'Mechanical Grip', tipKey: 'Wheel Rate Front' },
  'Mechanical Grip:Wheel Rate:  Rear': { category: 'Mechanical Grip', tipKey: 'Wheel Rate Rear' },
  'Mechanical Grip:Bumpstop Rate:  Front': { category: 'Mechanical Grip', tipKey: 'Bumpstop Rate Front' },
  'Mechanical Grip:Bumpstop Rate:  Rear': { category: 'Mechanical Grip', tipKey: 'Bumpstop Rate Rear' },
  'Mechanical Grip:Bumpstop Range:  Front': { category: 'Mechanical Grip', tipKey: 'Bumpstop Range Front' },
  'Mechanical Grip:Bumpstop Range:  Rear': { category: 'Mechanical Grip', tipKey: 'Bumpstop Range Rear' },

  // Dampers
  'Dampers:Bump:  Front': { category: 'Dampers', tipKey: 'Bump Front' },
  'Dampers:Bump:  Rear': { category: 'Dampers', tipKey: 'Bump Rear' },
  'Dampers:Fast Bump:  Front': { category: 'Dampers', tipKey: 'Fast Bump Front' },
  'Dampers:Fast Bump:  Rear': { category: 'Dampers', tipKey: 'Fast Bump Rear' },
  'Dampers:Rebound:  Front': { category: 'Dampers', tipKey: 'Rebound Front' },
  'Dampers:Rebound:  Rear': { category: 'Dampers', tipKey: 'Rebound Rear' },
  'Dampers:Fast Rebound:  Front': { category: 'Dampers', tipKey: 'Fast Rebound Front' },
  'Dampers:Fast Rebound:  Rear': { category: 'Dampers', tipKey: 'Fast Rebound Rear' },

  // Aero
  'Aero & Ride Height:Ride Height:  Front': { category: 'Aero & Ride Height', tipKey: 'Ride Height Front' },
  'Aero & Ride Height:Ride Height:  Rear': { category: 'Aero & Ride Height', tipKey: 'Ride Height Rear' },
  'Aero & Ride Height:Rake': { category: 'Aero & Ride Height', tipKey: 'Rake' },
  'Aero & Ride Height:Brake Ducts:  Front': { category: 'Aero & Ride Height', tipKey: 'Brake Ducts Front' },
  'Aero & Ride Height:Brake Ducts:  Rear': { category: 'Aero & Ride Height', tipKey: 'Brake Ducts Rear' },
  'Aero & Ride Height:Splitter': { category: 'Aero & Ride Height', tipKey: 'Splitter' },
  'Aero & Ride Height:Rear Wing': { category: 'Aero & Ride Height', tipKey: 'Rear Wing' },
}

// Special toe tip generation that considers positive/negative toe values
function getToeTip(
  tipKey: string,
  baselineVal: number,
  compareVal: number,
): string {
  const isRear = tipKey === 'Toe Rear'
  const basePos = baselineVal > 0.001
  const baseNeg = baselineVal < -0.001
  const compPos = compareVal > 0.001
  const compNeg = compareVal < -0.001

  if (Math.abs(compareVal - baselineVal) < 0.001) return ''

  if (isRear) {
    if (compNeg && basePos) return 'Switching from toe-out to toe-in on the rear. This significantly increases straight-line stability and reduces oversteer, but reduces corner rotation.'
    if (compPos && baseNeg) return 'Switching from toe-in to toe-out on the rear. This significantly increases corner rotation but reduces straight-line stability and can cause dangerous oversteer. Rear toe-out is almost never used in competitive ACC setups — verify this is intentional.'
    if (compPos && basePos) {
      return compareVal > baselineVal
        ? 'More rear toe-out. The car will rotate more in corners but may feel unstable at high speed. Rear toe-out is very rarely used in ACC — most competitive setups use toe-in or neutral.'
        : 'Less rear toe-out, moving toward neutral. The car will be more stable at high speed but rotate less in corners.'
    }
    if (compNeg && baseNeg) {
      return compareVal < baselineVal
        ? 'More rear toe-in. Greater straight-line stability and a more planted rear end, but the car resists rotation into corners.'
        : 'Less rear toe-in. Slightly more willingness to rotate in corners while still maintaining rear stability.'
    }
    if (compPos) return 'Rear toe has moved to toe-out. The car will rotate more in corners but may be less stable at high speed. This is an unusual choice in ACC — most setups use rear toe-in.'
    if (compNeg) return 'Rear toe has moved to toe-in. Greater straight-line stability and a more planted rear end, with less rotation in corners.'
    return 'Rear toe is now neutral — a balance between stability and rotation.'
  }

  // Front toe
  if (compPos && baseNeg) return 'Switching from toe-in to toe-out on the front. Turn-in response is much sharper as the front tyres are pre-angled to initiate rotation, but straight-line stability is reduced and the front tyres will scrub more, increasing wear.'
  if (compNeg && basePos) return 'Switching from toe-out to toe-in on the front. Straight-line stability is greatly improved and front tyre wear decreases, but initial turn-in response is slower.'
  if (compPos && basePos) {
    return compareVal > baselineVal
      ? 'More front toe-out. Even sharper turn-in response, but less straight-line stability and increased front tyre scrub and wear.'
      : 'Less front toe-out. Slightly calmer turn-in with a bit more straight-line stability and reduced tyre scrub.'
  }
  if (compNeg && baseNeg) {
    return compareVal < baselineVal
      ? 'More front toe-in. Greater straight-line stability, but the car may feel sluggish on initial turn-in as the front tyres resist the steering input.'
      : 'Less front toe-in. A bit more responsive on turn-in while retaining some straight-line stability.'
  }
  if (compPos) return 'Front toe has moved to toe-out. Better initial turn-in response but reduced straight-line stability.'
  if (compNeg) return 'Front toe has moved to toe-in. Better straight-line stability but slower initial turn-in.'
  return 'Front toe is now neutral — a balance between turn-in response and straight-line stability.'
}

export function getTipForParameter(
  categoryName: string,
  parentLabel: string,
  paramLabel: string,
  diff: DiffDirection,
  baselineNumeric?: number,
  compareNumeric?: number,
): string {
  if (diff === 'equal') return ''

  // Build the lookup key
  const key = parentLabel
    ? `${categoryName}:${parentLabel}:${paramLabel}`
    : `${categoryName}:${paramLabel}`

  const mapping = parameterTipMap[key]
  if (!mapping) return ''

  // Special toe handling
  if (mapping.tipKey === 'Toe Front' || mapping.tipKey === 'Toe Rear') {
    if (baselineNumeric !== undefined && compareNumeric !== undefined) {
      return getToeTip(mapping.tipKey, baselineNumeric, compareNumeric)
    }
    return ''
  }

  const tipEntry = tips[mapping.category]?.[mapping.tipKey]
  if (!tipEntry) return ''

  return diff === 'higher' ? tipEntry.higher : tipEntry.lower
}